name: Smooth Criminal
author: ada
public: true
flag: REP{4Nns_833N_H!t_bY_tH3_m4N_1N_tH3_M!Rr0r_8c30cec2db940e}
description: |-
  Your roommate, Ann Elizabeth Aryeuokei, is missing and you're about to be suspect #1. Find out everything you can about Ann and her life before the police pin her disappearance onto you. Start in a major social networking site.

  NOTE: DO NOT contact any real people. All accounts have been created in August/September 2024.