name: Angry Girlfriend
author: ada
public: true
attachments:
  - angry-girlfriend.zip
flag: REP{pR3tr4!n3D_gF_<3_m0v135_&_B19_v0caBu74ry}
description: |-
  Eh, your girlfriend angry. Faster go say sorry.

  nc <tbc>