apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-oracle-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-oracle-1
  template:
    metadata:
      labels:
        app: crypto-oracle-1
    spec:
      containers:
        - name: oracle
          image: keanekwa/repctf:crypto-oracle-1-v2
          ports:
            - containerPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-oracle-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-oracle-2
  template:
    metadata:
      labels:
        app: crypto-oracle-2
    spec:
      containers:
        - name: oracle
          image: keanekwa/repctf:crypto-oracle-2-v2
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-oracle-1
spec:
  type: ClusterIP
  selector:
    app: crypto-oracle-1
  ports:
    - protocol: TCP
      name: crypto-oracle-1
      port: 1337
      targetPort: 1337
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-oracle-2
spec:
  type: ClusterIP
  selector:
    app: crypto-oracle-2
  ports:
    - protocol: TCP
      name: crypto-oracle-2
      port: 1337
      targetPort: 1337
      protocol: TCP
# # ---
# # apiVersion: networking.k8s.io/v1
# # kind: Ingress
# # metadata:
# #   name: repctf-ingress
# #   annotations:
# #     kubernetes.io/ingress.class: nginx
# # spec:
# #   rules:
# #     - http:
# #         paths:
# #           - path: /crypto1
# #             pathType: Prefix
# #             backend:
# #               service:
# #                 name: crypto-oracle-1
# #                 port:
# #                   number: 1337
# #           - path: /crypto2
# #             pathType: Prefix
# #             backend:
# #               service:
# #                 name: crypto-oracle-2
# #                 port:
# #                   number: 1337
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-tcp-services
#   namespace: ingress-nginx
# data:
#   tcp-services: |
#     1337: default/service/crypto-oracle-1:1337
