apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: lostmodulus
spec:
  ports:
    - name: "30004"
      port: 30004
      targetPort: 1337
  selector:
    io.kompose.service: app
  type: LoadBalancer
  loadBalancerIP: "34.131.197.225"
status:
  loadBalancer: {}
