apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-oracle-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto-oracle-1
  template:
    metadata:
      labels:
        app: crypto-oracle-1
    spec:
      containers:
        - name: oracle
          image: keanekwa/repctf:crypto-oracle-1-v2
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-oracle-1
spec:
  type: ClusterIP
  selector:
    app: crypto-oracle-1
  ports:
    - protocol: TCP
      name: crypto-oracle-1
      port: 1337
      targetPort: 1337
      protocol: TCP
