name: Skibidi
author: ada
public: true
attachments:
  - skibidi-locations.zip
flag: REP{GUA_LON_POR_RWA_JER_KUC_GYE_BRU_WAL_SOA_MAR}
description: |-
  The Skibidi Toilets are winning in the violent Global Toilet Arms Race.
  Prove your worth in The Alliance by finding the locations of all 11 of their Toilet Hideouts.


  ~skibidi dop dop dop yes yes skibidi double u reeh reeh~