name: Capybara
author: ada
public: true
attachments:
  - capybara.wav
flag: REP{Lsb_5uBsT1tUt!0N_15_dUcK1n9_!NS3cuR3!}
description: |-
  1 in every 100 Capybara is the Littlest Significant Bara on earth.
  Capybara swim in channel too.
  Capybara speak 'nak nak!' like duck.


  I love capybara.